import type { Metadata } from "next";

import "@/sass/main.scss";
import { TaskHeader } from "@/components/Task/Header/TaskHeader";
import { Menu } from "@/components/Task/Menu/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="task">
      <TaskHeader />
      <div className="task__main">
        <Menu />
        {children}
      </div>
    </div>
  );
}
